/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('ant-design-vue/es')['Input']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NewTask: typeof import('./src/components/newTask.vue')['default']
    Task: typeof import('./src/components/Task.vue')['default']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
  }
}
